version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: myapp-image
    ports:
      - 8000:8000
    volumes:
      - ./Documents/youNoteCode:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: laravel_db
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: laravel_password
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - 3306:3306
    volumes:
      - ./db-data:/var/lib/mysql
